class AddDiscountAndStockToProduct < ActiveRecord::Migration[6.1]
  def change
    add_column :products, :stock, :integer
    add_column :products, :discount_percentage, :float
  end
end

# Generated by:
# rails g migration AddDiscountAndStockToProduct stock:integer discount_percentage:float
#
# ------------------------------------------------------------------------------------------
#
# Cambiar de nombre a una colunma, era más que sencillo (y ahi 
# lo "intuitivo" del desarrollo RoR)
# Es utilizando:
#
# rename_column(table_name, column_name, new_column_name)
#
# Para un caso como el de arrriba podría ser:
# rename_column(:products, :discount_percentage, :discount)
